apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICJhdXRoIjogImEybHlhV3hzTG5CMWNubG5hVzQ2WjJod1gwVlVjWGhOVWxkRmVYUnZVSEkxUXpOb2FtRnFXVzVLVTI5c1JreGpWelJJVXpGRldBPT0iCiAgICAgICAgICAgIH0KICAgICAgICB9LAoJImNyZWRTdG9yZSI6ICJkZXNrdG9wIiwKCSJleHBlcmltZW50YWwiOiAiZGlzYWJsZWQiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiLAoJInBsdWdpbnMiOiB7CgkJImRlYnVnIjogewoJCQkiaG9va3MiOiAiZXhlYyIKCQl9LAoJCSJzY291dCI6IHsKCQkJImhvb2tzIjogInB1bGwsYnVpbGR4IGJ1aWxkIgoJCX0KCX0sCgkiZmVhdHVyZXMiOiB7CgkJImhvb2tzIjogInRydWUiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
