apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICJhdXRoIjogIlVIVnllV2RwYmt0Rk9tZG9jRjlGVkhGNFRWSlhSWGwwYjFCeU5VTXphR3BoYWxsdVNsTnZiRVpNWTFjMFNGTXhSVmc9IgogICAgICAgICAgICB9CiAgICAgICAgfSwKCSJjcmVkU3RvcmUiOiAiZGVza3RvcCIsCgkiZXhwZXJpbWVudGFsIjogImRpc2FibGVkIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwKCSJwbHVnaW5zIjogewoJCSJkZWJ1ZyI6IHsKCQkJImhvb2tzIjogImV4ZWMiCgkJfSwKCQkic2NvdXQiOiB7CgkJCSJob29rcyI6ICJwdWxsLGJ1aWxkeCBidWlsZCIKCQl9Cgl9LAoJImZlYXR1cmVzIjogewoJCSJob29rcyI6ICJ0cnVlIgoJfQp9
type: kubernetes.io/dockerconfigjson
