@startuml
title Kino Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь системы умный дом")

System_Ext(RecommenderSystem, "Рекомендательная система")
System_Ext(KinoOwnerSystem, "Киновладельцы")

Container(WebApp, "Веб-интерфейс", "JavaScript", "Взаимодействие с пользователем")
Container(MobileApp, "Моб-интерфейс", "Swift", "Взаимодействие с пользователем")

Container_Boundary(AuthSystem, "Auth System") {
  Container(AuthApi, "Сервис Авторизации", "Golang", "Авторизация")
  Container(UserInfoApi, "User Info Service", "Golang", "Получение информации о пользователе")
  Container(DatabaseUser, "Database User", "PostgreSQL", "Данные о пользователе")
}

Container_Boundary(GatewaySystem, "Gateway System") {
  Container(GatewayApi, "Gateway Service", "Golang", "Gateway")
  Container(GatewayMobileApi, "Gateway Mobile Service", "Golang", "Gateway")
  Container(RedisGateway, "Redis Gateway", "Redis", "Кеширование данных систем")
}

Container_Boundary(KinoAccessSystem, "Kino Access System") {
  Container_Boundary(KinoSystem, "Kino System") {
    Container(KinoApi, "Киносервис", "Golang", "Набор кино")
    Container(DatabaseKino, "Database Kino", "PostgreSQL", "База с кинчиками")
    Container(TopicKinoInput, "Topic Kino Input", "Kafka","События")
    Container(TopicKinoOutput, "Topic Kino Output", "Kafka","События")
  }

  Container_Boundary(PaymentSystem, "Payment System") {
    Container(AggregatorApi, "Сервис Агрегатор Оплаты", "Golang", "Сервис Агрегатор Оплаты")
    Container(PaymentApi, "Сервис Оплаты", "Golang", "Сервис оплаты кино")
    Container(SubscriptionApi, "Сервис Подписок", "Golang", "Сервис подписок кино")
    Container(SalesApi, "Сервис Скидок", "Golang", "Сервис скидок кино")
    Container(DatabasePayment, "Database Payment", "PostgreSQL", "Данные об оплате")
    Container(TopicPaymentOutput, "Topic Payment Output", "Kafka","Оплата киновладельцам")
  }
}

Container_Boundary(MetadataSystem, "Metadata System") {
  Container(MetadataApi, "Metadata API", "API metadata")
  Container(DatabaseMetadata, "Database Metadata", "PostgreSQL", "Метаданные")
  Container(TopicRecommenderInput, "Topic Recommender Input", "Kafka","События")
  Container(TopicRecommenderOutput, "Topic Recommender Output", "Kafka","События")
}

Container_Boundary(TestingSystem, "Testing System") {
  Container(TestApi, "Test API", "API для тестирования")
  Container(DatabaseTest, "Database Test", "PostgreSQL", "Тестовый набор данных")
}

System(GatewayApi, "Gateway API", "API для работы с интерфейсами")
System(GatewayMobileApi, "Gateway Mobile API", "API для работы с моб.интерфейсами")
System(AuthApi, "Auth API", "API Авторизации")
System(UserInfoApi, "User Info API", "API информация пользователя")
System(MetadataApi, "Metadata API", "API метаданных")
System(TestApi, "Test API", "API тестовых данных")
System(KinoApi, "Kino API", "API кино")
System(AggregatorApi, "Aggregator API", "API Аггрегатор")


Rel(user, WebApp, "Использует приложение")
Rel(user, MobileApp, "Использует моб.приложение")
Rel(WebApp, GatewayApi, "Обмен данными с Gateway")
Rel(MobileApp, GatewayMobileApi, "Обмен данными с Gateway")

Rel(GatewaySystem, AuthSystem, "Провека токена")
Rel(GatewaySystem, MetadataSystem, "Получение метаданных")
Rel(GatewaySystem, TestingSystem, "Получение тестовых данных")
Rel(GatewaySystem, KinoAccessSystem, "Получение кино")

Rel(MetadataSystem, KinoAccessSystem, "Получение доступных фильмов")
Rel(RecommenderSystem, TopicRecommenderInput, "Получение рекомендательной информации")
Rel(KinoOwnerSystem, TopicKinoInput, "Получение фильмов")
Rel(TopicPaymentOutput, KinoOwnerSystem, "Оплата владельцам")

Rel(KinoSystem, PaymentSystem, "Получение информации о покупке кино")

'Rel GatewayApi
Rel(GatewayApi, RedisGateway, "Кэширование")
Rel(GatewayMobileApi, RedisGateway, "Кэширование")

'Rel AuthApi
Rel(UserInfoApi, DatabaseUser,"Сохранение/чтение")

'Rel KinoAccess
Rel(PaymentApi, AggregatorApi,"Сохранение/чтение")
Rel(SalesApi, AggregatorApi,"Сохранение/чтение")
Rel(SubscriptionApi, AggregatorApi,"Сохранение/чтение")
Rel(AggregatorApi, DatabasePayment,"Сохранение/чтение")
Rel(AggregatorApi, TopicPaymentOutput,"Сохранение/чтение")

Rel(KinoApi, DatabaseKino,"Сохранение/чтение")
Rel(TopicKinoInput, KinoApi,"Сохранение/чтение")
Rel(KinoApi, TopicKinoOutput,"Сохранение/чтение")

'Rel MetadataApi
Rel(MetadataApi, DatabaseMetadata,"Сохранение/чтение")
Rel(TopicRecommenderInput, MetadataApi,"Сохранение/чтение")
Rel(MetadataApi, TopicRecommenderOutput,"Сохранение/чтение")

'Rel TestApi
Rel(TestApi, DatabaseTest,"Сохранение/чтение")



@enduml